name: Gradle build

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout repository

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'

      - name: Gradle Wrapper validation
        uses: gradle/wrapper-validation-action@v1.1.0

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew

      - name: Publish Test Reports
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JUnit Tests
          path: "**/build/test-results/**/*.xml"
          reporter: java-junit
